package frc.robot;


public enum TestFiniteStates 
{
    IDLE,
    DRIVELEFTFRONT,
    DRIVERIGHTFRONT,
    DRIVERIGHTREAR,
    DRIVELEFTREAR,
    DRIVEMECANUM,
    SHOOT1SOLENOID,
    LASTHOPESOLENOID,
    LOWERBEAVERSOLENOID,
    FIREBEAVERSOLENOID,
    INTAKEMOTOR,
    STOP
}